[project]
name = "mcp-server-perplexity"
version = "0.2.3"
description = "MCP Server for the Perplexity API."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [ "mcp>=1.0.0",]

[project.urls]
Homepage = "https://github.com/tanigami/mcp-server-perplexity"
Repository = "https://github.com/tanigami/mcp-server-perplexity"

[[project.authors]]
name = "Hirofumi Tanigami"
email = "tanigami@teps.io"

[[project.authors]]
name = "Daniel Riccio"
email = "ricciodaniel98@gmail.com"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
mcp-server-perplexity = "mcp_server_perplexity:main"
