name: Publish Python Package

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # IMPORTANT: mandatory for trusted publishing
  actions: read    # Needed for downloading artifacts

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/mcp-perplexity

    steps:
    - name: Download built distributions
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
        github-token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/
        verbose: true 