name: Semantic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build python-semantic-release

    - name: Build package
      run: python -m build

    - name: Python Semantic Release
      id: release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        semantic-release version
        semantic-release publish

    - name: Store the distribution packages
      if: steps.release.outputs.released == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
        retention-days: 5
        compression-level: 9
        if-no-files-found: error

    # Trigger the PyPI publish workflow if a new release was created
    - name: Trigger PyPI publish workflow
      if: steps.release.outputs.released == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'pypi-publish.yml',
            ref: 'main'
          }) 