name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Hatch
      uses: pypa/hatch@install
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-semantic-release

    - name: Python Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@v8.7.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # Trigger the PyPI publish workflow if a new release was created
    - name: Trigger PyPI publish workflow
      if: steps.release.outputs.released == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'pypi-publish.yml',
            ref: 'main'
          }) 